# Naive Bayes Classifier

In [1]:
# import libraries
import numpy as np
import pandas as pd

In [6]:
data=pd.read_csv('play_tennis.csv')
data
data.drop(columns=['day'],inplace=True)

In [4]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [ ]:
# Problem 1
# Outlook=Sunny,Temp=Hot,Humidity=High,Wind=Weak
#Play or No Play

# Solution
# P(Yes|Sunny,Hot,High,Weak)=P(Sunny|Yes)*P(Hot|yes)*P(High|Yes)*P(Weak|Yes)*P(Yes)
# P(No|Sunny,Hot,High,Weak)=P(Sunny|No)*P(Hot|No)*P(High|No)*P(Weak|No)*P(No)
# Compare and decide using the maximum a posterior rule

In [7]:
#p(yes)
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [8]:
py=9/14
pn=5/19
print(py)
print(pn)

0.6428571428571429
0.2631578947368421

In [9]:
# outlook
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [19]:
pon=0
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [20]:
# temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [21]:
pcoolno=1/5
photno=2/5
pmildno=2/5

pcoolyes=3/9
photyes=4/9
pmildyes=4/9

In [22]:
# humidity

pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [23]:
phighno=4/5
pnormalno=1/5

phighyes=3/9
pnormalyes=6/9

In [24]:
# wind
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [25]:
pstrongno=3/5
pweakno=2/5

pstrongyes=3/9
pweakyes=6/9

In [26]:
# Q1 ans:
pyes=py*psy*photyes*phighyes*pweakyes
print(pyes)

0.014109347442680775

In [27]:
pn=pn*psn*photno*phighno*pweakno
print(pn)

0.020210526315789477

In [ ]:
# Conclusion:

# No play